// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://levsbjqbbvonqugrolqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxldnNianFiYnZvbnF1Z3JvbHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjA0MzAsImV4cCI6MjA2OTkzNjQzMH0.eBgLYEMKA8EZf9bDbrY9wtng54TiSPUhfWTU4MPFN44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});